# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1f67b06a3ee5f2edbc2acfde78df112b85e3696499ae285f673b04c753b504c1a2be6508381c8611da57c9c02f9cb36494d3268941c76e3825bae70bf562a75

test:
  secret_key_base: 7491de4a1f9b64752e2657bf30ad1223fcf5f490273ae12f7211f38372a67ad80d1dd38dd2cae87b5610a3db3e623b5de727380caa0fce16f6b657af90b94320

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
